### ISSUE TITLE
Solving using QMDP

### ISSUE THREAD

**Issue by pparmesh** [JuliaPOMDP/RockSample.jl#17]
Hi,
I'm trying to solve the example problem using QMDP and it looks like the simulation (or generated policy) gets stuck once it takes a measurement action. Any solver/problem settings that I might be missing?

**Comment by zsunberg** [comment]
I don't think you should need to change any settings for QMDP to work. It may produce some bad policies because QMDP is, in general, suboptimal though.

You may have more luck finding some help if you post a few more details, and the POMDPs.jl discussion page (https://github.com/JuliaPOMDP/POMDPs.jl/discussions) is more popular.

**Comment by MaximeBouton** [comment]
Rock sample requires some information gathering action, so I don't expect QMDP to work well on this problem, a discussion would be more appropriate.
