### ISSUE TITLE
python version of RockSample

### ISSUE THREAD

**Issue by initial-h** [JuliaPOMDP/RockSample.jl#37]
Hi,

Thanks for the open source. I want to try some recent DRL methods on RockSample task, for example DQN and PPO. Since these DRL methods are written in Python, I'm wondering if there is a Python implementation of RockSample (better with OpenAI Gym interface).

Thanks again.

**Comment by zsunberg** [comment]
There is not a python implementation that I know of. You can bridge between the two without too much trouble. You can convert this to a CommonRLInterface model with
```
import POMDPTools
using CommonRLInterface
convert(CommonRLInterface.AbstractEnv, RockSamplePOMDP())
```
and then you can wrap that in a gym environment with something like the code here: https://github.com/CU-ADCL/CU-DMU-Materials/blob/master/hw/5-Deep-Reinforcement-Learning/starter_code_py.py

We should probably have a package that does all this since it would be really convenient. Contributions welcome!
